services:
  - type: web
    name: adligpt-web
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: PORT
        value: 10000